### ISSUE TITLE
after logging in. 'This page isn’t working'

### ISSUE THREAD

**Issue by dufu1991** [cowboycodr/KianKit#12]
This page isn’t working

**Comment by cowboycodr** [comment]
Could you provide any more details? Maybe a screenshot?

**Comment by cowboycodr** [comment]
I'm assuming this is related to the problems addressed in #11.

**Comment by cowboycodr** [comment]
I'm working on a fix right now. #13.

**Comment by cowboycodr** [comment]
Should be resolved now. I improperly configured my redirect urls in my supabase dashboard.

**Comment by dufu1991** [comment]
The problem is still there. The same error after logging in with the GitHub account.

**Comment by cowboycodr** [comment]
That's very strange. It's happening for me as well, again. Let me do some investigating.

Are you also getting a screen like this?
![image](https://github.com/cowboycodr/KianKit/assets/59800761/d5c94dd6-4df8-4836-b460-4ccbde29462e)

**Comment by cowboycodr** [comment]
Never mind. I was being a bit of an idiot. I used wildcard domains for the primary site URL in the supabase dashboard which, apparently, doesn't work. 

So essentially, none of this would affect your site if you were to use this template. As for the demo site, it should now be fixed.

Sorry about that. Let me know if I can help with anything else.
